modLoader="javafml"
loaderVersion="[1,)"
license="GNU General Public License v3.0"

[[mods]]
modId="romaniansdelight"
version="0.7.0"
displayName="Romanian's Delight"
displayURL="https://github.com/zkamper/romanians-delight"
logoFile="logo.png"
logoBlur=false
description='''Addon for Farmer's Delight. Adds food and items with a Romanian theme.'''

[[dependencies.romaniansdelight]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.romaniansdelight]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.romaniansdelight]]
modId="farmersdelight"
type="required"
versionRange="[1.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.romaniansdelight]]
modId="culturaldelights"
type="required"
versionRange="[0.15.5,)"
ordering="NONE"
side="BOTH"
